name: GarciaPassingAgency
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8132216725498438
title: Garcia Passing Agency
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dae0e5'
    - '#9ea3b2'
    - '#7a7470'
    - '#3d2f22'
    - '#110100'
  brandStrength: 0.9231549564283341
  lightness: 0.7909865230321884
  saturation: 0.9282568274065852
  rhythmicContrast: 0.19079503836110234
purpose: []
